Skip caching if cache directory cannot be created
When the cache drive for `pgduck_server` is full, trying to
cache any new tables/files first may need to create the relevant
cache folder. But when the disk is full, users get the following
error on Postgres:

```
insert into public.events_iceberg select * from public.events_iceberg;select pg_size_pretty(lake_iceberg.table_size('public.events_iceberg'));
ERROR:  IO Error: Failed to create directory "/var/lib/duckdb/files/s3/6nmhen5cohitmhxoxoiyrspsmetujrxo/mxrx2fdbdfhn7ggc5uaevx4nee/postgres/public/events_iceberg/17538/data/0eb66c97-9b3f-4aa9-b587-0bd5d9baec14/": No space left on device
```

Instead, let's skip caching, and this commit implements that.